config/routes.rb
require 'sidekiq/web'

GitlabCi::Application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :help do 
    get :oauth2
  end

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
    end

    resources :services, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resource :charts, only: [:show]
    resources :commits, only: [:show] do
      member do
        get :status
      end
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :runners, only: [:index, :edit, :update, :destroy]
    resources :jobs, only: [:index]
  end

  resource :user_sessions do
    get :auth
    get :callback
  end

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
      end
    end

    resources :projects do
      resources :runner_projects
    end

    resources :builds, only: :index
  end

  root :to => 'projects#index'
end

app/views/notify/build_fail_email.html.haml
%p
  Build failed for
  = link_to project_url(@project) do
    = @project.name

%p
  Status: #{@build.status}
%p
  Commit: #{@build.commit.short_sha}
%p
  Author: #{@build.commit.git_author_name}
%p
  Branch: #{@build.commit.ref}
%p
  Message: #{@build.commit.git_commit_message}

%p
  Url: #{link_to @build.short_sha, project_build_url(@build.project, @build)}

app/views/notify/build_fail_email.text.erb
Build failed for <%= @project.name %>

Status:   <%= @build.status %>
Commit:   <%= @build.commit.short_sha %>
Author:   <%= @build.commit.git_author_name %>
Branch:   <%= @build.commit.ref %>
Message:  <%= @build.commit.git_commit_message %>

Url:      <%= project_build_url(@build.project, @build) %>

app/views/notify/build_success_email.html.haml
%p
  Build successful for
  = link_to project_url(@project) do
    = @project.name

%p
  Status: #{@build.status}
%p
  Commit: #{@build.commit.short_sha}
%p
  Author: #{@build.commit.git_author_name}
%p
  Branch: #{@build.commit.ref}
%p
  Message: #{@build.commit.git_commit_message}

%p
  Url: #{link_to @build.short_sha, project_build_url(@build.project, @build)}

app/views/notify/build_success_email.text.erb
Build successful for <%= @project.name %>

Status:   <%= @build.status %>
Commit:   <%= @build.commit.short_sha %>
Author:   <%= @build.commit.git_author_name %>
Branch:   <%= @build.commit.ref %>
Message:  <%= @build.commit.git_commit_message %>

Url:      <%= project_build_url(@build.project, @build) %>